### ISSUE TITLE
Exception There is no component field [field] in the given Query because of global variable

### ISSUE THREAD

**Issue by superdav42** [KnpLabs/knp-components#90]
I ran into a problem using the get param ?sort=date on almost any page of our site that throw the exception:
Exception There is no component field [date] in the given Query because of global variable in Knp\Component\Pager\Event\Subscriber\Sortable\Doctrine\ORM\Query:56

I traced the problem to:
https://github.com/KnpLabs/knp-components/blob/master/src/Knp/Component/Pager/Event/Subscriber/Sortable/Doctrine/ORM/QuerySubscriber.php#L16

Which uses the global $_GET to see if it should sort the result. The problem is it tries to sort queries that I never intended to sort. I'm actually using the sort param to sort a query that doesn't use the paginator but since it's a global it tries to sort other queries on the page that do use the paginator and throw this error. 

I fixed it by adding this to my config:

```
services:
    knp_paginator.subscriber.sortable:
        class: SomeDummyClass\SortableSubscriber
        scope: request
        tags:
             - { name: 'knp_paginator.subscriber' }      
```

where SomeDummyClass\SortableSubscriber just has empty before function and doesn't register any listeners.

I think all the Sortable subscribers should probably be rewritten to not use global variables and instead pull the sort fields and directions from the options. 

If there's a better way to work around this let me know but since I don't plan on using 
the sorting functions of the paginator turning of the subscribers seems like the best option.
